CREATE TABLE `dp_kfc_shops` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `cityEnName` varchar(50) NOT NULL DEFAULT '' COMMENT '城市英文名',
  `cityId` varchar(11) NOT NULL DEFAULT '' COMMENT '城市id',
  `cityName` varchar(50) NOT NULL DEFAULT '' COMMENT '城市名',
  `host_name` varchar(32) NOT NULL DEFAULT '' COMMENT '数据源域名',
  `shopId` varchar(20) NOT NULL DEFAULT '' COMMENT '店铺id',
  `shop_address` varchar(100) NOT NULL DEFAULT '' COMMENT '店铺地址',
  `longitude` varchar(11) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(11) NOT NULL DEFAULT '' COMMENT '纬度',
  `opening_date` varchar(64) NOT NULL DEFAULT '' COMMENT '开店日期',
  `comments_num` varchar(11) NOT NULL DEFAULT '' COMMENT '总评论数',
  `monthly_comments_num` varchar(11) NOT NULL DEFAULT '' COMMENT '月平均评论数',
  `total_score` varchar(11) NOT NULL DEFAULT '0' COMMENT '总评分',
  `taste` varchar(11) NOT NULL DEFAULT '0' COMMENT '口味',
  `surroundings` varchar(11) NOT NULL DEFAULT '0' COMMENT '环境',
  `service` varchar(11) NOT NULL DEFAULT '0' COMMENT '服务',
  `per_consumption` varchar(11) NOT NULL DEFAULT '0' COMMENT '人均消费',
  `shop_url` varchar(64) NOT NULL DEFAULT '' COMMENT '店铺URL',
  `file_path` varchar(64) NOT NULL DEFAULT '' COMMENT '本地路径',
  `status` varchar(11) NOT NULL DEFAULT '0' COMMENT '状态',
  `operate_time` varchar(32) NOT NULL DEFAULT '0' COMMENT '操作时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='dp数据';